version: '3'

services:
  kong:
    image: kong:0.12-alpine
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    ports:
      - 8000-8001:8000-8001
      - 8443-8444:8443-8444

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: kong
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /data/db
      POSTGRES_INITDB_XLOGDIR: /data/txnlog
    volumes:
      - ./db/data:/data/db
      - ./db/txnlog:/data/txnlog

  ui:
    image: pgbi/kong-dashboard
    command: "start --kong-url http://kong:8001"
    ports:
      - 8080:8080
